# Generated by Django 6.0 on 2025-12-18 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_size_alter_order_date_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 18, 15, 33, 27, 151327)),
        ),
    ]
